cos-qa/osf-selenium-tests

pages/dashboard.py
pages/project.py
tests/test_dashboard.py

Create tests for adding a project from the dashboard.
Add test for creating a project from dashboard
Add test to check the create project modal
Add beginnings of `ProjectPage`
None
https://openscience.atlassian.net/browse/OSF-8791

Feature/test create project [OSF-8791]

---

base/expected_conditions.py
base/locators.py

The `locator` and `BaseElement` code was getting a little messy due to the growing number of locator types.
This code adds a mandatory method `get_element` to all locators. This method is used in `__getattribute__` of `BaseElement` so that there no longer has to be a special case for different types of locators.
I also changed an argument throughout the locator code that used to be called `element` to `attribute_name`. This was to clarify that that argument was the name of the property created in the page object class.
Nothing in the actual tests should change. If any new locator classes are created (let's hope not) they would need a `get_element` method moving forward.
None

Clean up locators code

---

pages/login.py
pages/preprints.py
tests/test_preprints.py

My first preprints PR only had the default preprint workflow. Would be nice to also double check that Share is up and running for preprints. This PR adds that test.
This test is checking the workflow an actual user would go through to get to the search page. If this doesn't seem like a worthwhile test, can cut out the first part where we click 'search' in order to get to the discover page and instead just navigate directly to the discover page.
I also found that there were a lot of strange errors logging in with IE. It seems it was sending the wrong keys for my username. It was suggested that sometimes IE needs to wait until certain things are fully loaded to send keys to an input. Change was added to wait an extra .5 when logging in in IE. This will hopefully be removed in the future.
IE …

Test to check if preprints search is functioning [QA-78]

---

.travis.yml
api/osf_api.py
markers.py
pytest.ini
requirements.txt
settings.py
tasks/__init__.py
tests/conftest.py
tests/test_dashboard.py
tests/test_preprints.py
tests/test_project.py

Create a small set of smoke tests that can be run daily on production.
- Add `smoke_test` marker. This is for a very small set of tests to be run to check general functioning.
- Added `PREFERRED_NODE` environment variable. It allows tests to be run all on the same node - preserving guids. Tests cannot be run on production without `PREFERRED_NODE` being set.
- Added `dont_run_on_preferred_node` marker to stop changes to the `PREFERRED_NODE` that may effect other tests. This is hopefully temporary.
- Added `faker` so it's now easy to create randomized titles.
- Will have to make considerations for `PREFERRED_NODE` when adding more tests to the smoke tests.
- There are some tests missing from our `smoke_test`s we still need a V2 action on a node that's not making it public and checking OSF …

Production smoke tests

---

components/project.py
pages/project.py
tests/test_project.py

Add log widget test and clean up file widget test.
Add wait in `test_file_widget_loads` for loading indicator.
Add wait for page reload in `test_change_title`.
In the future, make sure to account for loading indicators.
https://openscience.atlassian.net/browse/QA-76

Add log widget test

---

api/osf_api.py
components/navbars.py
pages/base.py
pages/preprints.py
tests/test_preprints.py

Add core tests for branded preprints. This mostly involves checking if branded pages load.
- Add a fixture for grabbing all preprint providers
- Add a fixture for grabbing all providers with custom domains
- Add tests for the landing, discover, submit, and detail pages.
There are some changes to the preprint base pages that we may need to keep an eye on. The construction of branded urls is currently pretty fragile and convoluted.
It would also be nice moving forward to moving providers into pythosf rather than doing unprotected dictionary access of the API data received.
https://openscience.atlassian.net/browse/QA-98

Add custom preprint domain tests [QA-98]

---

base/expected_conditions.py
base/locators.py
pages/login.py
tests/test_meetings.py

In IE, selenium sometimes sends the wrong keys. Selenium said this was fixed. [It's not](https://github.com/SeleniumHQ/selenium/issues/4462#issuecomment-327181851). And I just want my tests to pass.
Give locators their own `send_keys` so that it can send keys to IE over and over again until they're the correct keys. You know, like an insane person. Don't worry, it eventually times out and gives up.
Hopefully will be easier moving forward for things to pass in IE. The lovely part is now an error is raised that will let me know if the tests failed because of this problem.
Nope

Add special case for send_keys in IE

---

api/osf_api.py
components/project.py
settings.py
tests/test_project.py

This will add a smoke test for the addons. It will use a node that is already connected to all the addons (or however many are working for us right now) and check if files from those addons still load. That way, if an addon stops working, we'll know within the day.
Add prod addons test.
These tests will also fail when authentication for an addon needs to be redone. This will need to be done manually.
None

Add production smoke test for addons

---

.env.example
pages/base.py
pages/landing.py
settings.py
tests/test_dashboard.py
tests/test_landing.py

Add a test for creating a user. (This one's currently for the landing page, but replace with a generic one once the generic sign up exists)
Add test that creates a user. Can only be run on the stagings (not on test or prod). 
Also pop in the registered reports landing page loading test.
None
https://openscience.atlassian.net/browse/QA-118
https://openscience.atlassian.net/browse/QA-93

Add create user test [QA-118]

---

pages/login.py
tests/test_login.py

Add a quick test for alternate ways to log into the OSF.
Add quick check for institutional and orcid login pages.
None
https://openscience.atlassian.net/browse/QA-67

Add test for alternate logins [QA-67]

---

pages/base.py
pages/login.py
pages/project.py
tests/conftest.py
tests/test_project.py

Add privacy tests for different users 
- Added privacy tests for user two.
- Replaced `expect_login_redirect` flag on BasePage's `goto` with the more generic `expect_redirect_to`.
From now on, one can choose what page is expected (as it is possible for there to be a redirect or an error) when you `goto` a page. The page is still expected to have the requested URL within it.
https://openscience.atlassian.net/browse/QA-79

Add privacy tests for non contributor user [QA-79]

---

tests/test_institutions.py

Since https://openscience.atlassian.net/browse/PLAT-1108 specifies that we should not redirect away from our custom institution domains, let's update our smoke tests to check that as well.
Add confirmation we are in fact on the custom domain.
None
None

Check that custom institution URL is maintained

---

pages/project.py
tests/test_project.py

Add core test for analytics page.
Add very basic test for the analytics page of a private project.
None
https://openscience.atlassian.net/browse/QA-70

Add core test for analytics page [QA-70]

---

pages/project.py
tests/test_project.py

Add a core functionality test for the forks page.
- Add forks page page object
- Add test that creates a fork from the forks page.
None
https://openscience.atlassian.net/browse/QA-58

Add forks page core functionality test [QA-58]

---

components/navbars.py
pages/quickfiles.py
pages/support.py
pages/user.py
tests/test_search.py

Small fixes to update failing tests, mostly due to emberization.
Adds better locators and adds waffle overrides to Developer Apps and Personal Access tokens. Fixes locator for share button on Quickfiles. Removes some unused code.
If waffle flags are removed, remove waffle overrides.
None

Update locators for newly emberized pages

---

.env.example

Update `.env.example` to document all settings and change a pythonism to a shellism.
* Remove python-style heredocs that don't parse as shell
* Document all setting vars from settings.py
* List options for settings with constrained values
Doc-only, no functional changes.
*None*

rewrite .env.example to be more descriptive

---

pages/project.py
pages/user.py

The account settings page is in the process of becoming fully 'emberized'. See ticket here: https://openscience.atlassian.net/browse/ENG-199. As these tickets complete development, we will have to update our tests to accommodate for any changes in tests and locators. 
This test covers the updates included in the following sections
* Account settings
* Personal access tokens 
* Developer apps
1 - Outdated locators have been updated to support embosfed pages
2 - Extra spacing has been added to meet flake8 standards
As development continues on the Embosfed User Settings, we will need to continually update this test for proper coverage. 
https://openscience.atlassian.net/browse/ENG-756

Update embosfed locators for user account settings

---

README.md
base/expected_conditions.py
settings.py
tasks/__init__.py

We don’t test in IE anymore -- remove all references to IE from the suite.
References to IE were removed.
Here are the files I touched:
`
tasks/__init__.py
103:def test_travis_msie(ctx, numprocesses=None):
105:    Run tests on the latest Microsoft Internet Explorer
108:    print('Testing modules in "{}" in MSIE'.format('tests'))
README.md
18:(Note: it is not suggested you run these tests in Safari or IE).
settings.py
105:    'msie': {'browser': 'IE', 'browser_version': '11', 'os': 'Windows', 'os_version': '10', 'resolution': '2048x1536'},
base/expected_conditions.py
30:    This is used for repeatedly attempting to send keys to IE because sometimes it sends the
Gnar:OSF-Integration-Tests ajlisk$ ack -i '(?:[^kr]ie|explorer)\b'
`
We explicitly don't support IE -- I updated the README.md to …

Remove references to IE

---

tests/test_project_files.py

This fix allows us to run 4 add-ons and runs across 3 separate browsers in parallel. All 3 browsers (different users) are connected to the same add-on accounts.  Renaming files to _action_browser_provider.txt_ no longer causes overlap between files.
1 - Update file names
2 - Update drag & drop delete method
3 - Fix spacing on api calls for cleaner view
There is still room to improve the test_project_files.py test. We can add support for remote-edge browser in the future.
We also currently have tickets in the backlog for more improvements
1. OSF Rename and Delete https://openscience.atlassian.net/browse/ENG-994
2. OSF Move & Copy https://openscience.atlassian.net/browse/ENG-996
3. OSF Download https://openscience.atlassian.net/browse/ENG-997 …

Add-on file collision fix

---

pages/preprints.py
pages/project.py
pages/user.py
tests/test_preprints.py
tests/test_project.py
tests/test_user.py

Originally we expected to update locators in test_user.py. After further troubleshooting, we found that the failures from _test_nothings_public_ were the result of leftover projects from Forks & Supplemental materials. So the tests were updated to perform a cleanup after each run. 
Sidenote: To help with troubleshooting in the future, each new project created via API now contains 2 tags:
1 - qatest
2 - name_of_the_test
1 - Delete the supplemental project created during _test_preprints.py::TestPreprintWorkflow_
2 - Delete the fork created during _test_project.py::test_create_fork_
3 - Added tags to newly created projects that specify the current test
https://openscience.atlassian.net/browse/ENG-1128
https://openscience.atlassian.net/browse/ENG-863

Clean up forks and supplemental materials

---

settings.py

Mind and Life have downgraded and decided to remove https://research.mindandlife.org/ from their DNS.
- Remove the expired custom domain.
N/A
https://openscience.atlassian.net/browse/ENG-

Remove Mind & Life custom domain

---

.travis.yml
requirements.txt
tasks/__init__.py

Split selenium tests into two stages to avoid hitting Travis's time limits.
Split non-prod travis testing into two stages.  Each stage gets an hour to run. Test files are split into two approixmately-equal sized groups and assigned to each stage.  Each stage tests the three browsers simultaneously.
* Remove unused and redundant tasks
* Remove unused and inappropriate pytest-xdist module and related code.
* Remove troublesome -rerunfailures module, shifting that responsibility to multiple pytest runs.
Stage two won't run unless stage one passes.  Parameterized testing will come in a later PR.  Can run targeted tests by modifying the `glob.glob` line in `tasks/__init__.py`.
Stolen from Charlie Bucket.

Split Travis builds into two stages

---

components/navbars.py
tasks/__init__.py

Fixed outdated locators in navbars test to use the new `data-test` css selectors. These outdated locators were causing our Master branch to fail. 
Update locators in logged out homepage navbar
- Home
- Preprints
- Registries
- Meetings
Fetch a new local branch
`git fetch <remote> pull/<PR_number>/head:<branch_name>`
`git fetch <remote> pull/87/head:fix/navbar-test`
Run this test using:
`pytest tests/test_navbar.py -s -v`
We may need to look into using more `data-test` selectors in our navbars test where applicable. 
https://openscience.atlassian.net/browse/ENG-1510

Update Navbars tests locators

---

tests/test_my_projects.py

Our test suite has encountered a bug with the My Projects page. We've documented the bug and linked the JIRA ticket below. In the meantime, we would like to skip the test to remove unhelpful failures during our test runs and improve the overall stability of our test suite. See linked ticket for more information. 
Use pytest's built in markers to temporarily skip the `My Projects page` test.
`git fetch <remote> pull/<PR_number>/head:<branch_name>`
`git fetch <remote> pull/96/head:bug/my-projects-page`
Run this test locally using
`pytest tests/test_my_projects.py -s -v`
This action will be reversed once the linked ticket is resolved.
https://openscience.atlassian.net/browse/ENG-1737

Skip My Projects page test using pytest markers

---

settings.py

Our test were initially set up to run using Edge version 17.0. After investigating edge-specific failures on Travis jobs, we found out that Edge versions 17.0 and 18.0 are no longer suited for running our test suite. We've updated to the latest stable version of Edge in `settings.py`
1 - Update browserstack's virtual browser from `Edge 17.0` to the latest stable version by removing `browser_version` variable
2 - Remove unused browsers
`git fetch <remote> pull/<PR_number>/head:<branch_name>`
`git fetch <remote> pull/103/head:feature/dashboard`
Run this test using
Modify your environment file
`DRIVER=Remote`
`TEST_BUILD=edge`
`BSTACK_USER=username`
`BSTACK_KEY=password`
For testing on production, also use
`DOMAIN=prod`
`PREFERRED_NODE=ra4bf`
`USER_ONE=Leemus_email` …

Browserstack Edge update

---

pages/cos.py

Due to recent changes with pathways and Hubspot, the donate page url has been updated. Our selenium tests are now updated to match the correct url on production. https://www.cos.io/about/support-cos
1 - Update the Donate Link URL
`git fetch <remote> pull/<PR_number>/head:<branch_name>`
`git fetch <remote> pull/112/head:feature/donate-page`
Run this test using
`tests/<name_of_test>.py -s -v`
`pytest tests/test_navbar.py::TestMeetingsNavbar::test_donate_link -s -v`
`pytest tests/test_navbar.py::TestOSFHomeNavbar::test_donate_link -s -v`
A note for future improvement and for thinking about how our selenium tests take care of legacy URLs. In this example, given that we have the legacy URL https://www.cos.io/support and the new URL https://www.cos.io/about/support-cos, is it selenium tests' …

Update Donate Link

---

tests/test_preprints.py
tests/test_project_files.py
utils.py

Selenium cannot detect the first search result of the Arabixiv preprint service **IF** the title is written in Arabic. This issue only happens in Firefox so Google Chrome and Microsoft Edge will still cover the default test case. Our goal is use an English-titled preprint in Firefox which can be done by searching for the term "Analysis" in the URL. 
1. Check browser for Firefox and Arabixiv preprint service
2. Search for the term "Analysis" and continue test normally
`git fetch <remote> pull/115/head:feature/arabixiv`
Run this test using
`pytest tests/test_preprints.py::TestBrandedProviders::test_detail_page -s -v`
N/A 
https://openscience.atlassian.net/browse/ENG-1800

Add search query to Firefox search results

---

tests/test_registries.py

Our browserstack test run shows that our test successfully sends the test string `QA Test` but does not submit the search query. Locally, we were able to achieve the same end result using the ENTER special key. In this PR, we will update the registries search test to explicitly send the ENTER key versus '\n'. 
- Change "QA Test\n" to "QA Test" + ENTER
`git fetch <remote> pull/120/head:feature/registries-search`
Run this test using
`tests/test_registries.py::TestRegistriesDiscoverPage::test_search_results_exist -v`
N/A
https://openscience.atlassian.net/browse/ENG-ENG-2305

Add ENTER key to registries search test
